### ISSUE TITLE
White background got back to default dark background

### ISSUE THREAD

**Issue by TeresaChou** [mjbvz/vscode-github-markdown-preview#1]
Once I activate it, the color of my preview window is changed to dark color(same as my workspace. I like the original github white background theme. How can I change it to that?

**Comment by mjbvz** [comment]
Please provide more details. This extension is what provides the white background in the preview and other github like styling

**Comment by Shogutora** [comment]
The background color is dark. As in this extension does not provide github style light background styling.

**Comment by maristgeek** [comment]
@TeresaChou, was this just from installation and you got your white theme back after a reload? I've noticed one at least one system that none of the extensions kicked in until after I reloaded the window.

**Comment by mjbvz** [comment]
Closing as more information and repro steps needed to investigate this

**Comment by jlestes** [comment]
If anyone comes to this issue later, I believe this might be an issue with conflicting extensions. I found that `learn-preview` from Microsoft was causing the issue with a white or black background border. There was another setting that controlled this behavior but had other consequences on the document preview width. My solution was to disable the `learn-preview` extension. Once doing so everything was working great! Thanks @mjbvz for your extensions! So helpful!
