### ISSUE TITLE
Add support for GitHub Dark Mode

### ISSUE THREAD

**Issue by blakegearin** [mjbvz/vscode-github-markdown-preview#10]
GitHub added a [dark mode](https://github.blog/changelog/2020-12-08-dark-mode-public-beta/) to the public beta in December 2020.

Adding support so it can be previewed in VS Code would be highly appreciated 🙂

**Comment by myxxmikeyxx** [comment]
I would love a dark mode. I stated using the VS Code built in one with the Markdown Emoji extension so it meets my needs since it uses dark mode if your VS code is in dark mode.

**Comment by Universumgames** [comment]
YES, this is definitely needed.

**Comment by mjbvz** [comment]
This was added in https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles

This extension pack that includes that extension
