### ISSUE TITLE
Footnotes were recently released to GitHub Markdown

### ISSUE THREAD

**Issue by Chrizpy** [mjbvz/vscode-github-markdown-preview#12]
[Footnotes](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) were recently added to GitHubs markdown, would be pretty sweet to have this in the extension as well :)

**Comment by mjbvz** [comment]
Should already be provided by https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes

Want to submit a PR that adds it to this extension  pack?

**Comment by Chrizpy** [comment]
> Should already be provided by https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes

Oh!

> Want to submit a PR that adds it to this extension pack?

Sure! I can take a look at it. 😄
