### ISSUE TITLE
Are these extensions really required to run remotely?

### ISSUE THREAD

**Issue by Purpzie** [mjbvz/vscode-github-markdown-preview#18]
I use WSL2 frequently, but I prefer keeping extensions installed in windows only if possible. I can understand if some of these need to run remotely, but considering they just change how markdown is rendered, I'm not sure if it's necessary.

![image](https://user-images.githubusercontent.com/25022704/156824050-5c40fe21-f4f1-49c4-b611-e1a1f3e62488.png)
![image](https://user-images.githubusercontent.com/25022704/156823956-afbb3aa2-671d-42d7-b2fb-5bed2a689425.png)

**Comment by mjbvz** [comment]
Yes, they modify VS Code's built-in markdown renderer which is run on the same machine that the workspace is stored on

**Comment by Purpzie** [comment]
Thank you for the information.
