### ISSUE TITLE
Error loading webview

### ISSUE THREAD

**Issue by patrick-5546** [mjbvz/vscode-github-markdown-preview#21]
When I have the Markdown preview tab open for a while, I occasionally encounter the following error: 

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

I still get this error if I try closing and reopening the tab, or using the "Developer: Reload Window" command. The only way I have been able to resolve this error is to manually close and reopen VS Code.

**Comment by mattbierner** [comment]
This is an upstream VS Code issue. Please file it against VS Code instead
