### ISSUE TITLE
Markdown files open in Preview mode

### ISSUE THREAD

**Issue by guylepage3** [mjbvz/vscode-github-markdown-preview#24]
Not sure if this is intentional or not but when I open my markdown files they are opening first in Preview mode by default. This may be fine for some folks but I feel they should open in edit mode by default with the ability to then view the file in Preview mode.  

If there is a setting to turn this on/off please advise. Thx.

**Comment by mjbvz** [comment]
This doesn't sound related to the extension. Please file an issue against VS Code

**Comment by guylepage3** [comment]
@mjbvz resolved. I uninstalled the extension and then re-installed it and it's working fine. Thx.
