### ISSUE TITLE
Codeblock with markdown table aligns perfectly in VS Code + Preview but not aligned in GitHub's Editor

### ISSUE THREAD

**Issue by ElijahLynn** [mjbvz/vscode-github-markdown-preview#27]
Mac: Codeblock with markdown table aligns perfectly in VS Code + Preview but not aligned in GitHub's Editor.

## VS Code
![image](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/1504756/174ca2e0-1bd4-4898-9858-cb5a9059d757)

## GitHub Editor
![image](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/1504756/7d710133-dffd-47ab-868d-3b6809d70e8a)

It is the same with or without a codeblock, fwiw. Maybe this is something to do with font selection/theme? Not something that can be fixed by this extension?

**Comment by jjspace** [comment]
This has nothing to do with the extensions. VSCode and _rendered_ codeblocks on GitHub use a [monospaced font](https://www.wikiwand.com/en/Monospaced_font) which means all characters (including spaces) are the same width. This is great for programming but can be less preferable for large blocks of text.
The GitHub editor uses a proportional font which means different characters have different widths. This is always fairly obvious with the space character as large chunks of spaces (like those in your table) will be spaced differently.
You can see the affect for yourself if you change the font in VSCode to a font that's not monospaced.

I'm not sure if it's possible to change the font per line in VSCode but even if it was I think it would be fairly undesirable to most devs (myself included). The part that matters is the _output_ which is shown in the VSCode markdown preview and I can confirm that matches the _rendered_ version of comments in GitHub.

**Comment by ElijahLynn** [comment]
Thank you so much for that explanation of what is going on! I was afraid that might be the case, and there really isn't anything that can be done about it. 

Closing.
