### ISSUE TITLE
:) is auto converted to the smiley emoji

### ISSUE THREAD

**Issue by Geet-George** [mjbvz/vscode-github-markdown-preview#3]
When I enter the character :) to the .md file, it is auto-converted to 😃.

The same page on GitHub maintains the original :)

**Comment by mjbvz** [comment]
Any you're sure its this extension?

**Comment by Geet-George** [comment]
Ahh... Sorry. It was because the Markdown Emoji extension was auto-installed along with this extension. I disabled that, and the problem is fixed. Thanks!
