### ISSUE TITLE
TOC is only rendered for ATX style headings

### ISSUE THREAD

**Issue by mwmahlberg** [mjbvz/vscode-github-markdown-preview#4]
**Behavior**

The TOC is only rendered for ATX style headings, like

```markdown
# First level
## Second level
### Third level
```

whereas setext style headings are ignored

```markdown
First
===
not rendered

Second
--------
not rendered

### Third
Rendered
```

**Problem**
Using ATX style headers is not allowed in various projects and most notably the default settings of the Markdown linter for VS Code.

**Expected behavior**

The TOC generator should also take setext style headers into consideration.

**Comment by mjbvz** [comment]
This extension does not include a TOC generator. Can you show a screenshot of the problem?

**Comment by mwmahlberg** [comment]
> This extension does not include a TOC generator. Can you show a screenshot of the problem?

Will do later this day... Strange, though.

**Comment by mwmahlberg** [comment]
Double checked -- wrong project. Just went by the name. Please take my apologies.

**Comment by mwmahlberg** [comment]
shd101wyy/vscode-markdown-preview-enhanced#401
