### ISSUE TITLE
Markdown preview traps keybindings/focus

### ISSUE THREAD

**Issue by mredigonda** [mjbvz/vscode-github-markdown-preview#5]
Hi! This is an awesome VSCode extension, thanks a lot for it, I use it everyday.

I faced an issue that doesn't allow me to effectively use common keybindings when I'm supposedly focusing on the tab that contains the preview (I hope this is your domain, but feel free to indicate me who to ping if this has nothing to do with the extension itself).

**How to reproduce:**

1. Open a tab for a markdown file
2. Use `CTRL + KV` to open the preview side-to-side
3. Use `CTRL + 1` to focus the `.md` file
4. Use `CTRL + 2` to focus the preview
5. Use `CTRL + 1` to focus the `.md` file
6. Use `CTRL + 2` to focus the preview
7. Keep doing this until the focus seems to get trapped into the preview

I find it strange because the focus appears to be trapped in the preview tab, but it actually doesn't listen for other keybindings such as `CTRL + W` that should close the tab.

Again, thank you very much for this awesome software.

**Comment by mjbvz** [comment]
This sounds like an issue with VS Code, not with this extension. Can you please file it against VS Code itself instead? Thanks.
