### ISSUE TITLE
Support for open source versions of VS Code.

### ISSUE THREAD

**Issue by DerekDick** [mjbvz/vscode-github-markdown-preview#6]
There are some open source versions of VS Code (like [code](https://www.archlinux.org/packages/?name=code) and [VS Codium](https://aur.archlinux.org/packages/vscodium-bin/) on Arch Linux) that use [the Open VSX registry](https://open-vsx.org/). Please consider uploading this popular extension to OpenVSX :smiley:

[reference](https://wiki.archlinux.org/index.php/Visual_Studio_Code#No_extensions_found)

**Comment by mjbvz** [comment]
I don't have resources to test/support other platforms

**Comment by DerekDick** [comment]
It is not about different platforms/operating systems. It's about the extension market. Perhaps you can have a look at [OpenVSX](https://open-vsx.org/). I believe it is not difficult for you to publish you awesome extensions on OpenVSX.
